#!/bin/bash
#SBATCH -A sens2025035
#SBATCH --job-name=trgt_pipeline
#SBATCH --output=trgt_pipeline_%j.log
#SBATCH --error=trgt_pipeline_%j.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G

module purge
module load bioinfo-tools
module load samtools/1.20
module load bcftools/1.20

python3 /home/eftih/scripts/trgt_pipeline.py \
  --bamfolder /proj/sens2025035/ONT_project/BAM \
  --reference /home/eftih/reference/hg38.fa \
  --repeats /home/eftih/reference/STRchive-disease-loci.hg38.TRGT.bed \
  --trgt ~/trgt-v4.1.0-x86_64-unknown-linux-gnu/trgt \
  --outdir /home/eftih/trgt_outputs \
  --samtools samtools \
  --bcftools bcftools
